### ISSUE TITLE
No window preview on wayland in Ubuntu 18.10

### ISSUE THREAD

**Issue by pvoid** [medenagan/window-corner-preview#12]
**Describe the bug**
I am on testing brunch. I can see the list of windows, but when I enable window preview nothing is shown. There are no errors related to the extension in the journal.

**To Reproduce**
1. Start wayland session
2. Enable preview of any window

**Expected behavior**
Window preview on the screen

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.10, GNOME 3.30.1, Wayland

**Comment by JavaWantaBe** [comment]
Same on Fedora 29 with GNOME 3.30.1, Wayland

**Comment by insan1k** [comment]
Same on arch GNOME 3.30.1

**Comment by insan1k** [comment]
Edit:  #9 resolved the issue for me

**Comment by insan1k** [comment]
Hey guys whilst I had success in using #9 to fix the problem in my home computer, this one manifested itself on my work computer Arch with GNOME 3.30.2  even if I use #9 it doesn't work. Where you guys recommend I find resources to troubleshoot and hopefully help to fix this issue?

**Comment by quentinus95** [comment]
@edgyer 

`journalctl -xe`

```
JS ERROR: Exception in callback for signal: activate: TypeError: global.screen is undefined
                                            _setThumbnail@/home/quentin/.local/share/gnome-shell/extensions/window-corner-preview@fabiomereu.it/extension.js:534:13
                                            wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                            _enable@/home/quentin/.local/share/gnome-shell/extensions/window-corner-preview@fabiomereu.it/extension.js:707:9
                                            wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                            set window@/home/quentin/.local/share/gnome-shell/extensions/window-corner-preview@fabiomereu.it/extension.js:670:9
                                            _onUserTriggered/</</<@/home/quentin/.local/share/gnome-shell/extensions/window-corner-preview@fabiomereu.it/extension.js:796:21
                                            _emit@resource:///org/gnome/gjs/modules/signals.js:128:27
                                            activate@resource:///org/gnome/shell/ui/popupMenu.js:175:9
                                            wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                            _onButtonReleaseEvent@resource:///org/gnome/shell/ui/popupMenu.js:127:9
```

I replaced all `global.screen` occurences with `global.display` in `/home/quentin/.local/share/gnome-shell/extensions/window-corner-preview@fabiomereu.it/extension.js`.

Now it works perfectly.

**Comment by insan1k** [comment]
thanks @quentinus95 bro I had no idea the extensions logged also to systemd \o/

**Comment by Resonious** [comment]
FWIW, I'm also running Arch with GNOME 3.30.2 and I had to comment out the `"use strict"` in order to get it to work.

**Comment by kode54** [comment]
I'm also running Arch with GNOME 3.30.2, and I'm not sure if I should disable that `"use strict"` line. Some apps work already, like Gnome Terminal, but Totem doesn't work.

E: It does "work", but for Totem, it just displays the title bar and an empty solid color fill where the video should be.

E2: Works just fine with mpv --gpu-context=wayland. Must be an issue specific to how Totem plays videos.

**Comment by medenagan** [comment]
This should be fixed with v.3
