### ISSUE TITLE
No windows showing on Windows list

### ISSUE THREAD

**Issue by KiloLiuton** [medenagan/window-corner-preview#8]
When I click the monkey icon on the taskbar and select the drop-down menu "Windows", no actions happen and no drop-down list shows up, even though I have multiple windows open.

I am using Arch Linux with the gnome Desktop Environment and installed the extensions through Firefox and the package chrome-gnome-shell-extensions.

**Comment by Kivarnis** [comment]
I am also having this issue on Manjaro. Gnome 3.30.1

**Comment by medenagan** [comment]
Hi @KiloLiuton @Kivarnis  please note a patch was provided some time ago and it was committed on the testing branch (v. 3). 

Have you already tried to replace the v.2 with the latest version?

**Comment by KiloLiuton** [comment]
Hi @medenagan , thanks for the response.
How can I force version v. 3? The readme file on the testing branch shows latest version as v. 2 to me. I recently tried reinstalling from the gnome shell extensions website but the problem persists.

**Comment by medenagan** [comment]
Hi @KiloLiuton, version 3 has not been submitted yet to the GNOME Shell Extensions team. An automatic installment is not available for now.

About the readme file, unfortunately it does not acknowledge these changes yet. But **extension.js** was updated and **metadata.json** shows v.3. 

If you want to _force_ the testing version being set up:

You need to find these two files on your system. You can look for their directory on a terminal with `locate window-corner-preview@fabiomereu.it` or you can press ALT + F2 from your desktop, type `lg` and choose Show source from the Extensions tab.

Normally the path is ~/.local/share/gnome-shell/extensions/window-corner-preview@fabiomereu.it.

You can just replace these 2 files mentioned above with their newer version and restart the shell by pressing ALT + F2 and typing `R`

**Comment by prestancedesign** [comment]
Hi @medenagan,

I had just testing the v3 on Ubuntu 18.10 and now I can see the list of windows but when I selected one, there is no preview did not show up..
Any clue ?

**Comment by gctrevino** [comment]
#9 Worked for me...  =D

**Comment by prestancedesign** [comment]
Me too ! Thx @gctrevino

**Comment by KiloLiuton** [comment]
I have substituted the files as suggested by @medenagan and it is working again, thanks!
